#SITE SETTINGS
baseurl: /bizkitpark
exclude: ['README.md']
include: ['_pages']
permalink: /:title/
title: Bizkit Park
description: Bizkit Park is earth’s mightiest Nu-Metal tribute band. Bizkit Park celebrates the entire era and party like it’s 1999!
keywords: bizkit park

#SOCIAL
facebook: https://www.facebook.com/bizkitparkofficial
youtube: https://www.youtube.com/channel/UC8EhvXmDBgFLTg2PymsePnw
instagram: https://www.instagram.com/bizkit_park
bandsintown: https://www.bandsintown.com/en/a/9582945-bizkit-park
photography: https://www.facebook.com/Sempiternalphotograph/
booking_be_mail: waldo@lsagency.be
booking_be_phone: +32 11 67 17 01
booking_eu_mail: benny@doomstarbookings.com
booking_eu_phone: +31 (0)6 546 822 87
promo: info@bizkitpark.be

#lANG NAVIGATION
navi:
- name: Home
  url: '#top'
  class:
  rel:
- name: Media
  url: '#media'
  class:
  rel:
- name: Shows
  url: '#shows'
  class: home
  rel:
- name: Bio
  url: '#bio'
  class:
  rel:
- name: Contact
  url: '#contact'
  class:
  rel:
